const CONFIG = {
  TASK: {
    DEFAULT_STATUS: 'OPEN',
    DEFAULT_PAGE_SIZE: 10,
    DEFAULT_CURRENT_PAGE: 1,
    DEFAULT_BACK_DAY: 90,
  },
  STATUS: {
    OPEN: 'OPEN',
    COMPLETED: 'COMPLETED',
    IN_PROGRESS: 'IN_PROGRESS',
  },
  MESSAGE: {
    TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  },
};

export { CONFIG };
